FROM python:3.11

WORKDIR ./

COPY ./requirements.txt .

RUN pip install --upgrade pip && \
pip install -r requirements.txt

COPY . ../api

ENV PYTHONPATH=/app:$PYTHONPATH
ENV PYTHONUNBUFFERED=1

CMD ["uvicorn", "api.app:app", "--host", "0.0.0.0", "--reload"]
